# Generated by Django 4.0.3 on 2022-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_social_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_instagram_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_twitter_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
