# Generated by Django 4.0.3 on 2022-03-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='live_demo_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
