# Generated by Django 4.0.3 on 2022-03-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tag_experties_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experties',
            name='description',
        ),
    ]
