# Generated by Django 4.0.3 on 2022-03-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_usermessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
    ]
